### ISSUE TITLE
$auth.loginWith() not working

### ISSUE THREAD

**Issue by yuruyuri16** [nuxt-community/auth-module#750]
### Version

[v4.9.1](https://github.com/auth-module/releases/tag/v4.9.1)

### Reproduction link

[https://codesandbox.io/s/nifty-shtern-4lbdo](https://codesandbox.io/s/nifty-shtern-4lbdo)

### Steps to reproduce

* Go to ```/login```
* In console you will have the following warnings

./.nuxt/auth/schemes/oauth2.js 142:24-30
"export 'default' (imported as 'nanoid') was not found in 'nanoid'
./.nuxt/auth/schemes/oauth2.js 155:30-36
"export 'default' (imported as 'nanoid') was not found in 'nanoid'

* Click on login with google

* In console you will see the following errors

TypeError: Object(...) is not a function
[Vue warn]: Failed to mount component: template or render function not defined.

### What is expected ?

to go to the google login page

### What is actually happening?

Nothing happens

### Additional comments?

I am using typescript for this project
I added '@types/nuxtjs__auth' to my package.json

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/auth-module/issues/c607">#c607</a>)</em></sub></div>

**Comment by heyshadowsmith** [comment]
I have encountered this as well, and I have found what I believe the issue is.

If you go to `./.nuxt/auth/schemes/oauth2.js` and update this line...
`import nanoid from 'nanoid'` to this...
import { nanoid } from 'nanoid', it works.

But the second Nuxt's hot reload kicks in, it will revert it back to the broken state.

**Comment by heyshadowsmith** [comment]
@yuruyuri16 I found a interim fix that works until this is patched!

I fixed this issue by adding nanoid 2.1.11 as a direct dependency in my project by running...
`npm i nanoid@2.1.11`

**Comment by Will-Burgon** [comment]
Thanks @heyshadowsmith, will try this later, been bugging me for the last few hours that I have to change the import of nanoid in the ` ./.nuxt/auth/schemes/oauth2.js` file everytime the app rebuilds.

**Comment by ziadomar97** [comment]
Hi, have you solved the problem؟

**Comment by Soviut** [comment]
@Will-Burgon you should never touch any of the files in the `.nuxt` directory.

**Comment by JeremyQtweb** [comment]
I have a similar problem where upgrading to Nanoid 3.3.4 causes nuxt/auth to fail with a 401 code, even though my package file still shows nuxt/auth depending on 2.1.11.

How can I use the latest version of Nanoid while nuxt/auth continues to work with the older version? I thought that's what it's supposed to do.

I've tried to do what I need with 2.1.11 but it's got it's own problems trying to use the generate module - the old requires notation fails with a TS related error and my project has no TS in it, so the workaround just isn't worth the hassle.
